# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_profile',
            old_name='LOCATION',
            new_name='ADDRESS',
        ),
        migrations.AddField(
            model_name='users_profile',
            name='CITY',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
