# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180902_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_profile',
            name='USERNAME',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
